export const countryCodes = [
    { country: 'Afghanistan', abbreviation: 'AF', calling_code: '+93' },
    { country: 'Albania', abbreviation: 'AL', calling_code: '+355' },
    { country: 'Algeria', abbreviation: 'DZ', calling_code: '+213' },
    { country: 'Andorra', abbreviation: 'AD', calling_code: '+376' },
    { country: 'Angola', abbreviation: 'AO', calling_code: '+244' },
    { country: 'Antigua and Barbuda', abbreviation: 'AG', calling_code: '+1-268' },
    { country: 'Argentina', abbreviation: 'AR', calling_code: '+54' },
    { country: 'Armenia', abbreviation: 'AM', calling_code: '+374' },
    { country: 'Australia', abbreviation: 'AU', calling_code: '+61' },
    { country: 'Austria', abbreviation: 'AT', calling_code: '+43' },
    { country: 'Azerbaijan', abbreviation: 'AZ', calling_code: '+994' },
    { country: 'Bahamas', abbreviation: 'BS', calling_code: '+1-242' },
    { country: 'Bahrain', abbreviation: 'BH', calling_code: '+973' },
    { country: 'Bangladesh', abbreviation: 'BD', calling_code: '+880' },
    { country: 'Barbados', abbreviation: 'BB', calling_code: '+1-246' },
    { country: 'Belarus', abbreviation: 'BY', calling_code: '+375' },
    { country: 'Belgium', abbreviation: 'BE', calling_code: '+32' },
    { country: 'Belize', abbreviation: 'BZ', calling_code: '+501' },
    { country: 'Benin', abbreviation: 'BJ', calling_code: '+229' },
    { country: 'Bhutan', abbreviation: 'BT', calling_code: '+975' },
    { country: 'Bolivia', abbreviation: 'BO', calling_code: '+591' },
    { country: 'Bosnia and Herzegovina', abbreviation: 'BA', calling_code: '+387' },
    { country: 'Botswana', abbreviation: 'BW', calling_code: '+267' },
    { country: 'Brazil', abbreviation: 'BR', calling_code: '+55' },
    { country: 'Brunei', abbreviation: 'BN', calling_code: '+673' },
    { country: 'Bulgaria', abbreviation: 'BG', calling_code: '+359' },
    { country: 'Burkina Faso', abbreviation: 'BF', calling_code: '+226' },
    { country: 'Burundi', abbreviation: 'BI', calling_code: '+257' },
    { country: 'Cabo Verde', abbreviation: 'CV', calling_code: '+238' },
    { country: 'Cambodia', abbreviation: 'KH', calling_code: '+855' },
    { country: 'Cameroon', abbreviation: 'CM', calling_code: '+237' },
    { country: 'Canada', abbreviation: 'CA', calling_code: '+1' },
    { country: 'Central African Republic', abbreviation: 'CF', calling_code: '+236' },
    { country: 'Chad', abbreviation: 'TD', calling_code: '+235' },
    { country: 'Chile', abbreviation: 'CL', calling_code: '+56' },
    { country: 'China', abbreviation: 'CN', calling_code: '+86' },
    { country: 'Colombia', abbreviation: 'CO', calling_code: '+57' },
    { country: 'Comoros', abbreviation: 'KM', calling_code: '+269' },
    { country: 'Congo (Congo-Brazzaville)', abbreviation: 'CG', calling_code: '+242' },
    { country: 'Congo (Democratic Republic)', abbreviation: 'CD', calling_code: '+243' },
    { country: 'Costa Rica', abbreviation: 'CR', calling_code: '+506' },
    { country: 'Croatia', abbreviation: 'HR', calling_code: '+385' },
    { country: 'Cuba', abbreviation: 'CU', calling_code: '+53' },
    { country: 'Cyprus', abbreviation: 'CY', calling_code: '+357' },
    { country: 'Czech Republic', abbreviation: 'CZ', calling_code: '+420' },
    { country: 'Denmark', abbreviation: 'DK', calling_code: '+45' },
    { country: 'Djibouti', abbreviation: 'DJ', calling_code: '+253' },
    { country: 'Dominica', abbreviation: 'DM', calling_code: '+1-767' },
    { country: 'Dominican Republic', abbreviation: 'DO', calling_code: '+1-809' },
    { country: 'East Timor (Timor-Leste)', abbreviation: 'TL', calling_code: '+670' },
    { country: 'Ecuador', abbreviation: 'EC', calling_code: '+593' },
    { country: 'Egypt', abbreviation: 'EG', calling_code: '+20' },
    { country: 'El Salvador', abbreviation: 'SV', calling_code: '+503' },
    { country: 'Equatorial Guinea', abbreviation: 'GQ', calling_code: '+240' },
    { country: 'Eritrea', abbreviation: 'ER', calling_code: '+291' },
    { country: 'Estonia', abbreviation: 'EE', calling_code: '+372' },
    { country: 'Eswatini (Swaziland)', abbreviation: 'SZ', calling_code: '+268' },
    { country: 'Ethiopia', abbreviation: 'ET', calling_code: '+251' },
    { country: 'Fiji', abbreviation: 'FJ', calling_code: '+679' },
    { country: 'Finland', abbreviation: 'FI', calling_code: '+358' },
    { country: 'France', abbreviation: 'FR', calling_code: '+33' },
    { country: 'Gabon', abbreviation: 'GA', calling_code: '+241' },
    { country: 'Gambia', abbreviation: 'GM', calling_code: '+220' },
    { country: 'Georgia', abbreviation: 'GE', calling_code: '+995' },
    { country: 'Germany', abbreviation: 'DE', calling_code: '+49' },
    { country: 'Ghana', abbreviation: 'GH', calling_code: '+233' },
    { country: 'Greece', abbreviation: 'GR', calling_code: '+30' },
    { country: 'Grenada', abbreviation: 'GD', calling_code: '+1-473' },
    { country: 'Guatemala', abbreviation: 'GT', calling_code: '+502' },
    { country: 'Guinea', abbreviation: 'GN', calling_code: '+224' },
    { country: 'Guinea-Bissau', abbreviation: 'GW', calling_code: '+245' },
    { country: 'Guyana', abbreviation: 'GY', calling_code: '+592' },
    { country: 'Haiti', abbreviation: 'HT', calling_code: '+509' },
    { country: 'Honduras', abbreviation: 'HN', calling_code: '+504' },
    { country: 'Hungary', abbreviation: 'HU', calling_code: '+36' },
    { country: 'Iceland', abbreviation: 'IS', calling_code: '+354' },
    { country: 'India', abbreviation: 'IN', calling_code: '+91' },
    { country: 'Indonesia', abbreviation: 'ID', calling_code: '+62' },
    { country: 'Iran', abbreviation: 'IR', calling_code: '+98' },
    { country: 'Iraq', abbreviation: 'IQ', calling_code: '+964' },
    { country: 'Ireland', abbreviation: 'IE', calling_code: '+353' },
    { country: 'Israel', abbreviation: 'IL', calling_code: '+972' },
    { country: 'Italy', abbreviation: 'IT', calling_code: '+39' },
    { country: 'Jamaica', abbreviation: 'JM', calling_code: '+1-876' },
    { country: 'Japan', abbreviation: 'JP', calling_code: '+81' },
    { country: 'Jordan', abbreviation: 'JO', calling_code: '+962' },
    { country: 'Kazakhstan', abbreviation: 'KZ', calling_code: '+7' },
    { country: 'Kenya', abbreviation: 'KE', calling_code: '+254' },
    { country: 'Kiribati', abbreviation: 'KI', calling_code: '+686' },
    { country: 'Korea, North', abbreviation: 'KP', calling_code: '+850' },
    { country: 'Korea, South', abbreviation: 'KR', calling_code: '+82' },
    { country: 'Kuwait', abbreviation: 'KW', calling_code: '+965' },
    { country: 'Kyrgyzstan', abbreviation: 'KG', calling_code: '+996' },
    { country: 'Laos', abbreviation: 'LA', calling_code: '+856' },
    { country: 'Latvia', abbreviation: 'LV', calling_code: '+371' },
    { country: 'Lebanon', abbreviation: 'LB', calling_code: '+961' },
    { country: 'Lesotho', abbreviation: 'LS', calling_code: '+266' },
    { country: 'Liberia', abbreviation: 'LR', calling_code: '+231' },
    { country: 'Libya', abbreviation: 'LY', calling_code: '+218' },
    { country: 'Liechtenstein', abbreviation: 'LI', calling_code: '+423' },
    { country: 'Lithuania', abbreviation: 'LT', calling_code: '+370' },
    { country: 'Luxembourg', abbreviation: 'LU', calling_code: '+352' },
    { country: 'Madagascar', abbreviation: 'MG', calling_code: '+261' },
    { country: 'Malawi', abbreviation: 'MW', calling_code: '+265' },
    { country: 'Malaysia', abbreviation: 'MY', calling_code: '+60' },
    { country: 'Maldives', abbreviation: 'MV', calling_code: '+960' },
    { country: 'Mali', abbreviation: 'ML', calling_code: '+223' },
    { country: 'Malta', abbreviation: 'MT', calling_code: '+356' },
    { country: 'Marshall Islands', abbreviation: 'MH', calling_code: '+692' },
    { country: 'Mauritania', abbreviation: 'MR', calling_code: '+222' },
    { country: 'Mauritius', abbreviation: 'MU', calling_code: '+230' },
    { country: 'Mexico', abbreviation: 'MX', calling_code: '+52' },
    { country: 'Micronesia', abbreviation: 'FM', calling_code: '+691' },
    { country: 'Moldova', abbreviation: 'MD', calling_code: '+373' },
    { country: 'Monaco', abbreviation: 'MC', calling_code: '+377' },
    { country: 'Mongolia', abbreviation: 'MN', calling_code: '+976' },
    { country: 'Montenegro', abbreviation: 'ME', calling_code: '+382' },
    { country: 'Morocco', abbreviation: 'MA', calling_code: '+212' },
    { country: 'Mozambique', abbreviation: 'MZ', calling_code: '+258' },
    { country: 'Myanmar', abbreviation: 'MM', calling_code: '+95' },
    { country: 'Namibia', abbreviation: 'NA', calling_code: '+264' },
    { country: 'Nauru', abbreviation: 'NR', calling_code: '+674' },
    { country: 'Nepal', abbreviation: 'NP', calling_code: '+977' },
    { country: 'Netherlands', abbreviation: 'NL', calling_code: '+31' },
    { country: 'New Zealand', abbreviation: 'NZ', calling_code: '+64' },
    { country: 'Nicaragua', abbreviation: 'NI', calling_code: '+505' },
    { country: 'Niger', abbreviation: 'NE', calling_code: '+227' },
    { country: 'Nigeria', abbreviation: 'NG', calling_code: '+234' },
    { country: 'North Macedonia', abbreviation: 'MK', calling_code: '+389' },
    { country: 'Norway', abbreviation: 'NO', calling_code: '+47' },
    { country: 'Oman', abbreviation: 'OM', calling_code: '+968' },
    { country: 'Pakistan', abbreviation: 'PK', calling_code: '+92' },
    { country: 'Palau', abbreviation: 'PW', calling_code: '+680' },
    { country: 'Palestine', abbreviation: 'PS', calling_code: '+970' },
    { country: 'Panama', abbreviation: 'PA', calling_code: '+507' },
    { country: 'Papua New Guinea', abbreviation: 'PG', calling_code: '+675' },
    { country: 'Paraguay', abbreviation: 'PY', calling_code: '+595' },
    { country: 'Peru', abbreviation: 'PE', calling_code: '+51' },
    { country: 'Philippines', abbreviation: 'PH', calling_code: '+63' },
    { country: 'Poland', abbreviation: 'PL', calling_code: '+48' },
    { country: 'Portugal', abbreviation: 'PT', calling_code: '+351' },
    { country: 'Qatar', abbreviation: 'QA', calling_code: '+974' },
    { country: 'Romania', abbreviation: 'RO', calling_code: '+40' },
    { country: 'Russia', abbreviation: 'RU', calling_code: '+7' },
    { country: 'Rwanda', abbreviation: 'RW', calling_code: '+250' },
    { country: 'Saint Kitts and Nevis', abbreviation: 'KN', calling_code: '+1-869' },
    { country: 'Saint Lucia', abbreviation: 'LC', calling_code: '+1-758' },
    { country: 'Saint Vincent and the Grenadines', abbreviation: 'VC', calling_code: '+1-784' },
    { country: 'Samoa', abbreviation: 'WS', calling_code: '+685' },
    { country: 'San Marino', abbreviation: 'SM', calling_code: '+378' },
    { country: 'Sao Tome and Principe', abbreviation: 'ST', calling_code: '+239' },
    { country: 'Saudi Arabia', abbreviation: 'SA', calling_code: '+966' },
    { country: 'Senegal', abbreviation: 'SN', calling_code: '+221' },
    { country: 'Serbia', abbreviation: 'RS', calling_code: '+381' },
    { country: 'Seychelles', abbreviation: 'SC', calling_code: '+248' },
    { country: 'Sierra Leone', abbreviation: 'SL', calling_code: '+232' },
    { country: 'Singapore', abbreviation: 'SG', calling_code: '+65' },
    { country: 'Slovakia', abbreviation: 'SK', calling_code: '+421' },
    { country: 'Slovenia', abbreviation: 'SI', calling_code: '+386' },
    { country: 'Solomon Islands', abbreviation: 'SB', calling_code: '+677' },
    { country: 'Somalia', abbreviation: 'SO', calling_code: '+252' },
    { country: 'South Africa', abbreviation: 'ZA', calling_code: '+27' },
    { country: 'South Sudan', abbreviation: 'SS', calling_code: '+211' },
    { country: 'Spain', abbreviation: 'ES', calling_code: '+34' },
    { country: 'Sri Lanka', abbreviation: 'LK', calling_code: '+94' },
    { country: 'Sudan', abbreviation: 'SD', calling_code: '+249' },
    { country: 'Suriname', abbreviation: 'SR', calling_code: '+597' },
    { country: 'Sweden', abbreviation: 'SE', calling_code: '+46' },
    { country: 'Switzerland', abbreviation: 'CH', calling_code: '+41' },
    { country: 'Syria', abbreviation: 'SY', calling_code: '+963' },
    { country: 'Taiwan', abbreviation: 'TW', calling_code: '+886' },
    { country: 'Tajikistan', abbreviation: 'TJ', calling_code: '+992' },
    { country: 'Tanzania', abbreviation: 'TZ', calling_code: '+255' },
    { country: 'Thailand', abbreviation: 'TH', calling_code: '+66' },
    { country: 'Togo', abbreviation: 'TG', calling_code: '+228' },
    { country: 'Tonga', abbreviation: 'TO', calling_code: '+676' },
    { country: 'Trinidad and Tobago', abbreviation: 'TT', calling_code: '+1-868' },
    { country: 'Tunisia', abbreviation: 'TN', calling_code: '+216' },
    { country: 'Turkey', abbreviation: 'TR', calling_code: '+90' },
    { country: 'Turkmenistan', abbreviation: 'TM', calling_code: '+993' },
    { country: 'Tuvalu', abbreviation: 'TV', calling_code: '+688' },
    { country: 'Uganda', abbreviation: 'UG', calling_code: '+256' },
    { country: 'Ukraine', abbreviation: 'UA', calling_code: '+380' },
    { country: 'United Arab Emirates', abbreviation: 'AE', calling_code: '+971' },
    { country: 'United Kingdom', abbreviation: 'GB', calling_code: '+44' },
    { country: 'United States', abbreviation: 'US', calling_code: '+1' },
    { country: 'Uruguay', abbreviation: 'UY', calling_code: '+598' },
    { country: 'Uzbekistan', abbreviation: 'UZ', calling_code: '+998' },
    { country: 'Vanuatu', abbreviation: 'VU', calling_code: '+678' },
    { country: 'Vatican City', abbreviation: 'VA', calling_code: '+379' },
    { country: 'Venezuela', abbreviation: 'VE', calling_code: '+58' },
    { country: 'Vietnam', abbreviation: 'VN', calling_code: '+84' },
    { country: 'Yemen', abbreviation: 'YE', calling_code: '+967' },
    { country: 'Zambia', abbreviation: 'ZM', calling_code: '+260' },
    { country: 'Zimbabwe', abbreviation: 'ZW', calling_code: '+263' }
  ]
  